import certificate01 from "@/public/assets/svg/certificate-01.svg?svgr";
import switchhorizontal01 from "@/public/assets/svg/switch-horizontal-01.svg?svgr";
import slashcircle01 from "@/public/assets/svg/slash-circle-01.svg?svgr";
import bookopen01 from "@/public/assets/svg/book-open-01.svg?svgr";
import graduationhat01 from "@/public/assets/svg/graduation-hat-01.svg?svgr";
import announcement01 from "@/public/assets/svg/announcement-01.svg?svgr";
import plus01 from "@/public/assets/svg/plus.svg?svgr";
import share06 from "@/public/assets/svg/share-06.svg?svgr";
import user01 from "@/public/assets/svg/user-01.svg?svgr";
import archive01 from "@/public/assets/svg/archive.svg?svgr";
import clockFastForward from "@/public/assets/svg/clock-fast-forward.svg?svgr";
import star05 from "@/public/assets/svg/star-05.svg?svgr";
import barChart from "@/public/assets/svg/bar-chart-square-02.svg?svgr";
import homeLine from "@/public/assets/svg/home-line.svg?svgr";
import checkbox_unchecked from "@/public/assets/svg/checkbox_base_uncheck.svg?svgr";
import checkbox_checked from "@/public/assets/svg/checkbox_base_checked.svg?svgr";
import bookmark from "@/public/assets/svg/bookmark.svg?svgr";
import bookmark_check from "@/public/assets/svg/bookmark_checked.svg?svgr";
import helpIcon from "@/public/assets/svg/help_icon.svg?svgr";

export const Certificate = certificate01;
export const SwitchHorizontal = switchhorizontal01;
export const SlashCircle = slashcircle01;
export const BookOpen = bookopen01;
export const GraduationHat = graduationhat01;
export const Announcement = announcement01;
export const Plus = plus01;
export const Share = share06;
export const User = user01;
export const Archive = archive01;
export const ClockFastForward = clockFastForward;
export const Star = star05;
export const BarChart = barChart;
export const HomeLine = homeLine;
export const CheckBoxChecked = checkbox_checked;
export const CheckBoxUnChecked = checkbox_unchecked;
export const Bookmark = bookmark;
export const BookmarkChecked = bookmark_check;
export const HelpIcon = helpIcon;
